### ISSUE TITLE
Class 'Roots\Sage\Assets\JsonManifest' not found

### ISSUE THREAD

**Issue by davekiss** [roots/sage#1634]
Hey fellas,

Trying out Sage for the first time, on `dev-branch-9` and am getting a fatal error:

```
TASK [deploy : Update WP theme paths] ******************************************
PHP Fatal error:  Uncaught Error: Class 'Roots\Sage\Assets\JsonManifest' not
found in /srv/www/example.com/releases/20160405172020/web/app/themes/example/src/helpers.php:37
Stack trace:
#0 /srv/www/example.com/releases/20160405172020/web/app/themes/example/
src/setup.php(65): App\asset_path('main.css')
#1 /srv/www/example.com/releases/20160405172020/web/wp/wp-
includes/plugin.php(525): WP_CLI\Runner->App\{closure}('')
#2 phar:///usr/bin/wp/php/wp-settings-cli.php(391):
do_action('after_setup_the...')
#3 phar:///usr/bin/wp/php/WP_CLI/Runner.php(807):
require('phar:///usr/bin...')
#4 phar:///usr/bin/wp/php/commands/eval.php(23):
WP_CLI\Runner->load_wordpress()
#5 [internal function]: Eval_Command->__invoke(Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67):
call_user_func(Array, Array, Array)
#7 [internal function]:
WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(351):
call_user_func(Object(Closure),  in /srv/www/example.com/releases/20160405
172020/web/app/themes/example/src/helpers.php on line 37
Fatal error: Uncaught Error: Class 'Roots\Sage\Assets\JsonManifest' not found
in /srv/www/example.com/releases/20160405172020/web/app/themes/example/
src/helpers.php:37
Stack trace:
#0 /srv/www/example.com/releases/20160405172020/web/app/themes/example/
src/setup.php(65): App\asset_path('main.css')
#1 /srv/www/example.com/releases/20160405172020/web/wp/wp-
includes/plugin.php(525): WP_CLI\Runner->App\{closure}('')
#2 phar:///usr/bin/wp/php/wp-settings-cli.php(391):
do_action('after_setup_the...')
#3 phar:///usr/bin/wp/php/WP_CLI/Runner.php(807):
require('phar:///usr/bin...')
#4 phar:///usr/bin/wp/php/commands/eval.php(23):
WP_CLI\Runner->load_wordpress()
#5 [internal function]: Eval_Command->__invoke(Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67):
call_user_func(Array, Array, Array)
#7 [internal function]:
WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(351):
call_user_func(Object(Closure),  in /srv/www/example.com/releases/20160405
172020/web/app/themes/example/src/helpers.php on line 37
fatal: [ip.addr]: FAILED! => {"changed": true, "cmd": ["wp", "eval", "wp_clean_themes_cache(); switch_theme(get_stylesheet());"], "delta": "0:00:00.373618", "end": "2016-04-05 17:22:11.754606", "failed": true, "rc": 255, "start": "2016-04-05 17:22:11.380988", "stderr": "PHP Fatal error:  Uncaught Error: Class 'Roots\\Sage\\Assets\\JsonManifest' not found in /srv/www/example.com/releases/20160405172020/web/app/themes/example/src/helpers.php:37
Stack trace:
#0 /srv/www/example.com/releases/20160405172020/web/app/themes/example/src/setup.php(65): App\\asset_path('main.css')
#1 /srv/www/example.com/releases/20160405172020/web/wp/wp-includes/plugin.php(525): WP_CLI\\Runner->App\\{closure}('')
#2 phar:///usr/bin/wp/php/wp-settings-cli.php(391): do_action('after_setup_the...')
#3 phar:///usr/bin/wp/php/WP_CLI/Runner.php(807): require('phar:///usr/bin...')
#4 phar:///usr/bin/wp/php/commands/eval.php(23): WP_CLI\\Runner->load_wordpress()
#5 [internal function]: Eval_Command->__invoke(Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\\Dispatcher\\CommandFactory::WP_CLI\\Dispatcher\\{closure}(Array, Array)
#8 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(351): call_user_func(Object(Closure),  in /srv/www/example.com/releases/20160405172020/web/app/themes/example/src/helpers.php on line 37
Fatal error: Uncaught Error: Class 'Roots\\Sage\\Assets\\JsonManifest' not found in /srv/www/example.com/releases/20160405172020/web/app/themes/example/src/helpers.php:37
Stack trace:
#0 /srv/www/example.com/releases/20160405172020/web/app/themes/example/src/setup.php(65): App\\asset_path('main.css')
#1 /srv/www/example.com/releases/20160405172020/web/wp/wp-includes/plugin.php(525): WP_CLI\\Runner->App\\{closure}('')
#2 phar:///usr/bin/wp/php/wp-settings-cli.php(391): do_action('after_setup_the...')
#3 phar:///usr/bin/wp/php/WP_CLI/Runner.php(807): require('phar:///usr/bin...')
#4 phar:///usr/bin/wp/php/commands/eval.php(23): WP_CLI\\Runner->load_wordpress()
#5 [internal function]: Eval_Command->__invoke(Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\\Dispatcher\\CommandFactory::WP_CLI\\Dispatcher\\{closure}(Array, Array)
#8 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(351): call_user_func(Object(Closure),  in /srv/www/example.com/releases/20160405172020/web/app/themes/example/src/helpers.php on line 37", "stdout": "", "stdout_lines": [], "warnings": []}
```

I am deploying with Trellis and my `build-before.yml` looks like this:

```
- name: Run npm install
  command: npm install
  connection: local
  args:
    chdir: "{{ project.local_path }}/web/app/themes/example"

- name: Compile assets for production
  command: npm run build:production
  connection: local
  args:
    chdir: "{{ project.local_path }}/web/app/themes/example"

- name: Copy project local files
  synchronize:
    src: "{{ project.local_path }}/web/app/themes/example/dist"
    dest: "{{ deploy_helper.new_release_path }}/web/app/themes/example"
    group: no
    owner: no
    rsync_opts: --chmod=Du=rwx,--chmod=Dg=rx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=r,--chmod=Fo=r
```

Any ideas as to what I'm missing here?
Thanks as always!

**Comment by retlehs** [comment]
you'll also need to run `composer install` from the theme directory

**Comment by davekiss** [comment]
@retlehs I did actually have a `composer install` task in `build-before.yml` but removed it after it did not resolve the issue

**Comment by davekiss** [comment]
hmm. just `ssh`'d in and manually ran `composer install` and it seemed to correct the issue. I'll start a discussion over on the Trellis repo regarding updated `build-before.yml` defaults for sage 9

Cheers!

**Comment by AdamWills** [comment]
@davekiss - I might suggest the discussion happen over at the forums at https://discourse.roots.io/ - that's generally the best place for support/discussion.

**Comment by ptrckvzn** [comment]
Maybe you ran composer on the local machine instead of the remote? This works for me : 

```
- name: Install Composer dependencies
  command: composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --no-scripts
  args:
    chdir: "{{ deploy_helper.new_release_path }}/web/app/themes/sage"
```
