### ISSUE TITLE
[Sage 9] - Why use BrowserSync and not webpack-dev-server on 0.0.0.0 with a proxy-target?

### ISSUE THREAD

**Issue by jaredpalmer** [roots/sage#1660]

**Comment by ptrckvzn** [comment]
Would there be any advantages to using webpack-dev-server?

I find BrowserSync works well, has a nice interface and is easy to access from other devices. And, from memory when I worked on the Sage/webpack config, I found webpack-dev-server to be too much oriented toward js app and Sage is not that.

**Comment by asuh** [comment]
BrowserSync has better features, allows for multiple device testing out of the box, includes a great admin panel for more control and bandwidth throttling which is helpful to test for speed and loading. I see no reason to switch.

**Comment by jaredpalmer** [comment]
Despite the affiliation to Trellis, thanks to Docker for Mac/Windows Beta, a vanilla wordrpess site or even a bedrock config is one command away `docker-compose up -d`. However, Browsersync is pretty weird to configure inside of docker, webpack is much less so.

**Comment by retlehs** [comment]
@jaredpalmer i haven't yet dug into docker (finally bout to) so i'm not sure what steps are needed in order to get browsersync working with it. can you provide more details?

normally it's recommended to run node on the host machine and not on your vm/dev box. is that not the case with docker?

**Comment by Jeger** [comment]
@jaredpalmer @retlehs I run wordpress in docker, and i just run webpack on the outside. No problem.

**Comment by jaredpalmer** [comment]
@jeger Do you mind sharing your `docker-compose.yml` file?

If I recall, I was using a very very early version Docker for Mac Beta when I filed this issue when there was a bug in the native file watcher. Regardless, I still think browser-sync is kinda overkill.

**Comment by jaredpalmer** [comment]
If I recall, mine looked like this:

```yaml
web:
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "8080:80"
    volumes:
     - ./plugins:/var/www/html/wp-content/plugins
     - ./themes:/var/www/html/wp-content/themes
mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
```
