### ISSUE TITLE
Running npm run start doesnt update styles

### ISSUE THREAD

**Issue by tarabusk** [roots/sage#1856]
When I try to update the styles for my theme I do not see the changes update.

```bash
# inside my theme folder
npm run start
```

I can see the site fine and it initializes with the correct styles.

Then I make a changes to `main.scss`

```scss
// inside main.scss
// ...

// make everything pink
* {
 color: pink;
}
```

The problem is that the styles dont update. I see them in the original color instead of pink. If I stop the service and run `npm run start` again I will see pink.
