### ISSUE TITLE
[Question] How to use in WP ?

### ISSUE THREAD

**Issue by boskiv** [roots/sage#1900]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

![screen shot 2017-06-02 at 08 30 36](https://cloud.githubusercontent.com/assets/1939783/26712123/c8b5500c-476d-11e7-830a-7266d3a447d2.png)

**What is the expected or desired behavior?**

Hello. I have install 9.0.0-rc3 
`composer create-project roots/sage sage dev-master`
but there is no index.php or styles css in root. When I mount theme dir into /themes/ in WP, wp writes there is no style.css. What is current workflow to make sage theme installable ?

---

**Please describe your local environment:**

WordPress version: 4.7.5

OS: OSX

docker-compose file:

```
version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./sage:/var/www/html/wp-content/themes/sage

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
```

**Comment by boskiv** [comment]
If I try to user resources dir as root dir in theme 
```
version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./sushinroll/resources:/var/www/html/wp-content/themes/sushinroll

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
```
i've got an error
![screen shot 2017-06-02 at 08 38 23](https://cloud.githubusercontent.com/assets/1939783/26712300/f0ef44c8-476e-11e7-9666-6884f43560f6.png)
